In [1]:
company_name_list = [{'name': 'Company 1'},
          {'name': 'Company 2'},
          {'name': 'Company 3'}]

employee_name_list = [{'name': 'John Doe'},
          {'name': 'Tom Smith'},
          {'name': 'Andrew Sebastian'}]

company_detail_list = {
      'Company 1': {
          'name': 'Company 1',
          'domain': 'Retail',
          'clients': [
              {
                  'name': 'acme.inc',
                  'country': 'united states'
              },
              {
                  'name': 'Wayne.co',
                  'country': 'united states'
              }
          ]
      },
      'Company 2': {
          'name': 'Company 2',
          'domain': 'Construction',
          'clients': [
              {
                  'name': 'Tesla',
                  'country': 'united states'
              },
              {
                  'name': 'Japan Airlines',
                  'country': 'japan'
              },
              {
                  'name': 'Indofood',
                  'country': 'indonesia'
              }
          ]
      },
      'Company 3': {
          'name': 'Company 3',
          'domain': 'Healthcare',
          'clients': [
              {
                  'name': 'Petronas',
                  'country': 'malaysia'
              },
              {
                  'name': 'VW Group',
                  'country': 'germany'
              },
              {
                  'name': 'IBM',
                  'country': 'united states'
              },
              {
                  'name': 'Mitsubishi',
                  'country': 'japan'
              }
          ]
      }
  }

employee_detail_list = {
      'John Doe': {
          'name': 'EMP-0001',
          'first_name': 'John',
          'last_name': 'Doe',
          'full_name': 'John Doe',
          'company': 'Company 1'
      },
      'Tom Smith': {
          'name': 'EMP-0002',
          'first_name': 'Tom',
          'last_name': 'Smith',
          'full_name': 'Tom Smith',
          'company': 'Company 2'
      },
      'Andrew Sebastian': {
          'name': 'EMP-0003',
          'first_name': 'Andrew',
          'last_name': 'Sebastian',
          'full_name': 'Andrew Sebastian',
          'company': 'Company 2'
      },
  }

In [2]:
def sort_company(company_list):
    for company_name, company_detail in company_detail_list.items():
        print("Name:", company_detail['name'])
        print("Domain:", company_detail['domain'])
        print()

company_detail_list = {
      'Company 1': {
          'name': 'Company 1',
          'domain': 'Retail'},
    'Company 2': {
          'name': 'Company 2',
          'domain': 'Construction'},
     'Company 3': {
          'name': 'Company 3',
          'domain': 'Healthcare'}}
     

   
sort_company(company_detail_list)

Name: Company 1
Domain: Retail

Name: Company 2
Domain: Construction

Name: Company 3
Domain: Healthcare



In [ ]:
Soal no 2


In [ ]:
def get_company_domain(company_detail_list):
    for company_name, details in company_detail_list.items():
        domain = details['domain']
        num_clients = len(details['clients'])
        print(f"{company_name}: {domain}, relation: {num_clients} clients")
get_company_domain(company_detail_list)

In [ ]:
soal no 3

In [ ]:
def print_employee_company_domain():
    for employee_name, employee_detail in employee_detail_list.items():
        company_name = employee_detail['company']
        company_domain = company_detail_list[company_name]['domain']
        full_name = employee_detail['full_name']
        print(f'"full_name": "{full_name}", "company": "{company_name}", "domain": "{company_domain}"')

# Memanggil fungsi untuk mencetak detail karyawan, perusahaan, dan domain
print_employee_company_domain()

In [ ]:
Soal no 4

In [6]:
def get_employees_by_company():
 

  companies_with_employees = []
  for company_name, company_detail in company_detail_list.items():
    employees = [emp for emp, details in employee_detail_list.items() if details['company'] == company_name]
    company_info = {
      "company": company_name,
      "employees": employees
    }
    companies_with_employees.append(company_info)

  

  return companies_with_employees  # Optional, if you need the list returned


get_employees_by_company()


[{'company': 'Company 1', 'employees': ['John Doe']},
 {'company': 'Company 2', 'employees': ['Tom Smith', 'Andrew Sebastian']},
 {'company': 'Company 3', 'employees': []}]

In [ ]:
soal prepropessing 

In [8]:
import pandas
import numpy
from sklearn.preprocessing import LabelEncoder, OneHotEncoder, StandardScaler
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer 

In [12]:
data_startups = pandas.read_csv('50_startups.csv')
data_startups.sample(7)

R&D Spend  Administration  Marketing Spend     State     Profit
48     542.05        51743.15              NaN  New York   35673.41
2   153441.51       101145.55        407934.54   Florida  191050.39
22   73994.56       122782.75        303319.26   Florida  110352.25
3   144372.41       118671.85        383199.62  New York  182901.99
14  119943.24       156547.42        256512.92   Florida  132602.65
4   142107.34        91391.77        366168.42   Florida  166187.94
17   94657.16       145077.58        282574.31  New York  125370.37

In [ ]:
analisa nilai mean


In [13]:
X = data_startups.sample(7).values
X

array([[64664.71, 139553.16, 137962.62, 'California', 107404.34],
       [75328.87, 144135.98, 134050.07, 'Florida', 105733.54],
       [93863.75, 127320.38, 249839.44, 'Florida', 141585.52],
       [46014.02, 85047.44, 205517.64, 'New York', 96479.51],
       [15505.73, 127382.3, 35534.17, 'New York', 69758.98],
       [28754.33, 118546.05, 172795.67, 'California', 78239.91],
       [nan, 116983.8, 45173.06, 'California', 14681.4]], dtype=object)

In [14]:
label_encoder = LabelEncoder()
X[:, -2] =label_encoder.fit_transform(X[:,0])
X

array([[64664.71, 139553.16, 137962.62, 3, 107404.34],
       [75328.87, 144135.98, 134050.07, 4, 105733.54],
       [93863.75, 127320.38, 249839.44, 5, 141585.52],
       [46014.02, 85047.44, 205517.64, 2, 96479.51],
       [15505.73, 127382.3, 35534.17, 0, 69758.98],
       [28754.33, 118546.05, 172795.67, 1, 78239.91],
       [nan, 116983.8, 45173.06, 6, 14681.4]], dtype=object)

In [15]:
one_hot_encoder = OneHotEncoder(categories=X[0])
ct = ColumnTransformer([("Datastartup", OneHotEncoder(),[0])], remainder="passthrough")
X = ct.fit_transform(X)
df = pandas.DataFrame(X)
df

0    1    2    3    4    5    6          7          8  9          10
0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  139553.16  137962.62  3  107404.34
1  0.0  0.0  0.0  0.0  1.0  0.0  0.0  144135.98  134050.07  4  105733.54
2  0.0  0.0  0.0  0.0  0.0  1.0  0.0  127320.38  249839.44  5  141585.52
3  0.0  0.0  1.0  0.0  0.0  0.0  0.0   85047.44  205517.64  2   96479.51
4  1.0  0.0  0.0  0.0  0.0  0.0  0.0   127382.3   35534.17  0   69758.98
5  0.0  1.0  0.0  0.0  0.0  0.0  0.0  118546.05  172795.67  1   78239.91
6  0.0  0.0  0.0  0.0  0.0  0.0  1.0   116983.8   45173.06  6    14681.4

In [16]:
X=X.astype(int)
X

array([[     0,      0,      0,      1,      0,      0,      0, 139553,
        137962,      3, 107404],
       [     0,      0,      0,      0,      1,      0,      0, 144135,
        134050,      4, 105733],
       [     0,      0,      0,      0,      0,      1,      0, 127320,
        249839,      5, 141585],
       [     0,      0,      1,      0,      0,      0,      0,  85047,
        205517,      2,  96479],
       [     1,      0,      0,      0,      0,      0,      0, 127382,
         35534,      0,  69758],
       [     0,      1,      0,      0,      0,      0,      0, 118546,
        172795,      1,  78239],
       [     0,      0,      0,      0,      0,      0,      1, 116983,
         45173,      6,  14681]])

In [23]:
sc = StandardScaler()
X = sc.fit_transform(X)
X

array([[-0.40824829, -0.40824829, -0.40824829,  2.44948974, -0.40824829,
        -0.40824829, -0.40824829,  0.93856478, -0.02959088,  0.        ,
         0.53671735],
       [-0.40824829, -0.40824829, -0.40824829, -0.40824829,  2.44948974,
        -0.40824829, -0.40824829,  1.19388496, -0.0831266 ,  0.5       ,
         0.4912079 ],
       [-0.40824829, -0.40824829, -0.40824829, -0.40824829, -0.40824829,
         2.44948974, -0.40824829,  0.25691226,  1.50144578,  1.        ,
         1.46763204],
       [-0.40824829, -0.40824829,  2.44948974, -0.40824829, -0.40824829,
        -0.40824829, -0.40824829, -2.09864215,  0.89489924, -0.5       ,
         0.23917652],
       [ 2.44948974, -0.40824829, -0.40824829, -0.40824829, -0.40824829,
        -0.40824829, -0.40824829,  0.26036705, -1.43131798, -1.5       ,
        -0.48856612],
       [-0.40824829,  2.44948974, -0.40824829, -0.40824829, -0.40824829,
        -0.40824829, -0.40824829, -0.23199637,  0.4470987 , -1.        ,
        -0.257